import type { ReactNode, MouseEvent } from 'react';
import { Link } from 'react-router-dom';
import { ChevronRight, PackageCheck, ShoppingCart } from 'lucide-react';
export const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
export function Pill({children,tone}:{children:ReactNode;tone?:'teal'|'violet'}){return <span className={`pill ${tone||''}`}>{children}</span>}
export function ProductCard({product}:{product:any}){
 const add=(e:MouseEvent)=>{e.preventDefault();e.stopPropagation();const cart=JSON.parse(localStorage.getItem('cart')||'[]');const i=cart.findIndex((x:any)=>x.product_id===product.id);if(i>=0)cart[i].quantity+=1;else cart.push({product_id:product.id,quantity:1,product});localStorage.setItem('cart',JSON.stringify(cart));localStorage.setItem('cart_count',String(cart.reduce((s:any,x:any)=>s+x.quantity,0)));window.dispatchEvent(new Event('cart-changed'));};
 return <article className="product-card glass-card"><Link to={`/product/${product.id}`} className="product-card-link"><div className="product-image-wrap"><img src={`/product-images/${product.id}.svg`} alt=""/><span className="image-badge"><PackageCheck size={12}/> {product.available>0?'In stock':'Out of stock'}</span></div><div className="product-info"><div className="product-overline"><span>{product.category_name}</span><span>{product.sku}</span></div><h3>{product.name}</h3><p>{product.brand_name} · {product.pack_size}</p></div></Link><div className="product-footer"><div><span>OUR PRICE</span><strong>{money(Number(product.our_selling_price))}</strong><small>Market {money(Number(product.market_benchmark_price))}</small></div><button className="add-btn" onClick={add} title="Add to cart"><ShoppingCart size={16}/></button></div><div className="product-bottom"><span>{product.available>0?`${product.available} available`:'Restock required'}</span><Link to={`/product/${product.id}`}>View <ChevronRight size={13}/></Link></div></article>
}
