from decimal import Decimal
from sqlalchemy import select
from app.db.session import Base, engine, SessionLocal
from app.models import *
from app.core.security import hash_password

CATALOG = [
("Diagnostic Instruments","GI Straight Probe Single Ended",25),("Diagnostic Instruments","GI Explorer Double Ended",190),("Diagnostic Instruments","GDC Probe Explorer Double Ended",510),("Diagnostic Instruments","Waldent Straight Probe No.6",125),("Diagnostic Instruments","Waldent WHO Probe",130),("Diagnostic Instruments","Goldman Fox + Williams Probe",145),("Diagnostic Instruments","GI Mouth Mirror with Handle Pack 10",375),("Diagnostic Instruments","GI Probe + Mouth Mirror + Tweezer",89),("Diagnostic Instruments","GDC PMT Set #4",1235),("Diagnostic Instruments","GDC Marium Tweezer",230),("Diagnostic Instruments","Samit Mouth Mirror and Handle",179),("Diagnostic Instruments","GI Mouth Mirror Tops Pack 10",300),("Diagnostic Instruments","GDC Magnified Mirror Tops Pack 12",860),("Diagnostic Instruments","GDC Marking Probe",190),("Diagnostic Instruments","Diagnostic PMT Set Premium",665),("Diagnostic Instruments","Waldent PMT Kit",270),("Diagnostic Instruments","London College Tweezer",200),("Diagnostic Instruments","Explorer Single Ended",190),("Diagnostic Instruments","DG16 Endodontic Explorer",250),("Diagnostic Instruments","Mirror Handle",120),
("Periodontal","GDC Manipal Scaler Set of 3",570),("Periodontal","Williams Periodontal Probe",130),("Periodontal","WHO Periodontal Probe",130),("Periodontal","Goldman Fox Probe",145),("Periodontal","Gracey Curette Single",300),("Periodontal","Gracey Curette Set",9400),("Periodontal","Gracey Curette S/9 Kit",11760),("Periodontal","Hu-Friedy Gracey 11/12",2065),("Periodontal","Periodontal Maintenance Set",660),("Periodontal","Universal Scaler",180),("Periodontal","Sickle Scaler",180),("Periodontal","Jacquette Scaler",200),("Periodontal","Area Specific Curette",300),("Periodontal","Periodontal Probe",150),("Periodontal","Furcation Probe",300),
("Restorative","Spoon Excavator",150),("Restorative","Double End Excavator",250),("Restorative","Amalgam Condenser",250),("Restorative","Ball Burnisher",250),("Restorative","Egg Burnisher",250),("Restorative","Hollenback Carver",300),("Restorative","Cleoid Discoid Carver",350),("Restorative","Composite Placement Instrument",750),("Restorative","Titanium Composite Instrument",1000),("Restorative","Composite Instrument Set",5385),("Restorative","GDC Composite Posterior Set",6485),("Restorative","Cement Spatula",150),("Restorative","GIC Spatula",150),("Restorative","Mixing Pad",100),("Restorative","Dappen Dish",120),("Restorative","Tofflemire Retainer",350),("Restorative","Matrix Band Pack",150),("Restorative","Sectional Matrix Kit",2000),("Restorative","Wooden Wedges Pack",150),("Restorative","Articulating Paper",250),("Restorative","Cotton Pliers",150),("Restorative","Amalgam Carrier",450),("Restorative","Cavity Liner",400),("Restorative","Calcium Hydroxide Liner",500),("Restorative","Caries Excavator Fine",180),
("Dental Materials","D-Tech Restore GIC",390),("Dental Materials","Shofu FX Ultra GIC",1060),("Dental Materials","3M Ketac Molar GIC",1730),("Dental Materials","3M Ketac Universal",2860),("Dental Materials","Shofu Glasionomer RX",1605),("Dental Materials","Zirconomer Improved",2429),("Dental Materials","GC Gold Label GIC",2943),("Dental Materials","Ammdent GIC Luting",1835),("Dental Materials","Ammdent GIC Fill",1835),("Dental Materials","Composite Resin Universal",1200),("Dental Materials","Flowable Composite",645),("Dental Materials","Nano Hybrid Composite",900),("Dental Materials","Bonding Agent",900),("Dental Materials","Universal Adhesive",1200),("Dental Materials","Etchant Gel",300),("Dental Materials","Calcium Hydroxide Cement",650),("Dental Materials","MTA Repair Material",1200),("Dental Materials","Temporary Filling Material",500),("Dental Materials","Provisional Crown Material",1200),("Dental Materials","Resin Cement",1800),
("Endodontics","K-File Assorted",250),("Endodontics","H-File Assorted",300),("Endodontics","Reamer",250),("Endodontics","Finger Spreader",250),("Endodontics","Plugger",249),("Endodontics","Lentulo Spiral",500),("Endodontics","Gates Glidden Drills",500),("Endodontics","Peeso Reamers",500),("Endodontics","Endo Ruler",150),("Endodontics","Endo Measuring Block",250),("Endodontics","Paper Points",200),("Endodontics","Gutta Percha 2%",190),("Endodontics","Gutta Percha 4%",230),("Endodontics","Gutta Percha 6%",230),("Endodontics","Protaper Gutta Percha",967),("Endodontics","Meta Gutta Percha",173),("Endodontics","Sure Endo Gutta Percha",270),("Endodontics","SuperEndo Blue Files Pack 6",835),("Endodontics","Gold Rotary Files",835),("Endodontics","Rotary Files Premium",1000),("Endodontics","Retreatment Files",1090),("Endodontics","Endo Bur Kit",616),("Endodontics","Safe-End Bur Kit",610),("Endodontics","Endodontic Sealer",1200),("Endodontics","Irrigation Needles",300),("Endodontics","Irrigation Syringes",250),("Endodontics","Endo Spreader Set",500),("Endodontics","Endo Plugger Set",500),("Endodontics","Endo Stopper",250),("Endodontics","Endomotor",7000),("Endodontics","Apex Locator",8000),("Endodontics","Endomotor + Apex Locator Combo",11500),
("Rubber Dam / Isolation","Rubber Dam Clamp Adult",390),("Rubber Dam / Isolation","Rubber Dam Clamp Paedo",390),("Rubber Dam / Isolation","Rubber Dam Forceps",1560),("Rubber Dam / Isolation","Rubber Dam Punch",1975),("Rubber Dam / Isolation","Rubber Dam Frame",540),("Rubber Dam / Isolation","Rubber Dam Sheet Adult",780),("Rubber Dam / Isolation","Rubber Dam Sheet Paedo",780),("Rubber Dam / Isolation","Rubber Dam Clamp Kit",3615),("Rubber Dam / Isolation","Rubber Dam Kit 21 Piece",6195),("Rubber Dam / Isolation","Rubber Dam Adult Kit",11070),("Rubber Dam / Isolation","Rubber Dam Template",1480),("Rubber Dam / Isolation","Rubber Dam Wedge Cord",315),("Rubber Dam / Isolation","Rubber Dam Clamp Set 11",5635),
("Surgical / Extraction","Dental Surgical Scissors",95),("Surgical / Extraction","Needle Holder",455),("Surgical / Extraction","TC Needle Holder",2275),("Surgical / Extraction","Scalpel Pack 10",115),("Surgical / Extraction","Luxating Hybrid",1975),("Surgical / Extraction","Upper Premolar Forceps",820),("Surgical / Extraction","Upper Pedo Molar Forceps",1075),("Surgical / Extraction","Upper Anterior Pedo Forceps",1075),("Surgical / Extraction","Universal Extraction Forceps",500),("Surgical / Extraction","Root Elevator Straight",250),("Surgical / Extraction","Root Elevator Curved",350),("Surgical / Extraction","Cryer Elevator",450),("Surgical / Extraction","Warwick James Elevator",500),("Surgical / Extraction","Periosteal Elevator",450),("Surgical / Extraction","Bone Rongeur",1500),("Surgical / Extraction","Bone File",750),("Surgical / Extraction","Tissue Forceps",300),("Surgical / Extraction","Hemostat",450),("Surgical / Extraction","Surgical Curette",500),("Surgical / Extraction","Surgical Retractor",600),("Surgical / Extraction","Extraction Forceps Kit 12",8380),
("Orthodontics","Orthodontic Kit 11 Piece",7125),("Orthodontics","De La Rosa Pliers",885),("Orthodontics","Ligature Tucker",355),("Orthodontics","Pin and Ligature Cutter",1465),("Orthodontics","Weingart Pliers",900),("Orthodontics","Bird Beak Pliers",800),("Orthodontics","Distal End Cutter",1400),("Orthodontics","Hard Wire Cutter",1800),("Orthodontics","Bracket Removing Pliers",900),("Orthodontics","Band Seater",700),("Orthodontics","Band Removing Pliers",900),("Orthodontics","Elastic Separators Pack",480),("Orthodontics","Ligature Ties",195),("Orthodontics","Intraoral Elastics",65),("Orthodontics","E-Chain",245),("Orthodontics","NiTi Archwire",500),("Orthodontics","Molar Bands",800),("Orthodontics","Orthodontic Bracket Set",1500),("Orthodontics","Power Chain",300),
("Prosthodontics / Impression","Impression Compound Pack 5",150),("Prosthodontics / Impression","Aquasil Impression Material",1200),("Prosthodontics / Impression","Impression Compound Sticks",180),("Prosthodontics / Impression","Impression Paste",300),("Prosthodontics / Impression","Spacer Wax",149),("Prosthodontics / Impression","Heavy Body Silicone",2000),("Prosthodontics / Impression","Light Body Silicone",1800),("Prosthodontics / Impression","Bite Registration Material",1000),("Prosthodontics / Impression","Tray Adhesive",700),("Prosthodontics / Impression","Stock Impression Tray Set",1000),
("Infection Control / Disposables","3-Ply Mask Pack 50",100),("Infection Control / Disposables","Nitrile Gloves Pack 100",285),("Infection Control / Disposables","Black Nitrile Gloves Pack 80",269),("Infection Control / Disposables","Cotton Rolls",150),("Infection Control / Disposables","Saliva Ejectors Pack 100",300),("Infection Control / Disposables","Dental Bibs Pack 100",500),("Infection Control / Disposables","Micro Applicators",250),("Infection Control / Disposables","Disposable Trays",500),("Infection Control / Disposables","Dental Needles Box 100",500),("Infection Control / Disposables","Sterilization Pouches",400),("Infection Control / Disposables","Sterilization Indicator Strips",300),("Infection Control / Disposables","Surface Disinfectant",500),("Infection Control / Disposables","Suction Tips",600),("Infection Control / Disposables","Cheek Retractors",500),("Infection Control / Disposables","Prophy Cups Pack",300),
("Finishing / Polishing","Polishing Strips",1085),("Finishing / Polishing","Sof-Lex Intro Kit",9205),("Finishing / Polishing","Finishing & Polishing Kit",1290),("Finishing / Polishing","Polishing Kit Premium",1399),("Finishing / Polishing","Polishing Strips Universal Kit",465),("Finishing / Polishing","Composite Polishing Burs",680),("Finishing / Polishing","Composite Finishing Disc",500),("Finishing / Polishing","Mandrels",200),("Finishing / Polishing","Silicone Polisher Set",800),("Finishing / Polishing","Rubber Polishers",500),
("Equipment","Dental Chair",159995),("Equipment","Dental Air Compressor",15990),("Equipment","Portable Dental X-Ray",119999),("Equipment","Autoclave 18L",48000),("Equipment","Airotor",2100),("Equipment","Premium Airotor",4900),("Equipment","Micromotor Kit",2995),("Equipment","Straight Handpiece",1500),("Equipment","Contra-Angle Handpiece",1500),("Equipment","Dental Suction Unit",43700),("Equipment","Light Curing Unit",2200),("Equipment","Ultrasonic Scaler",5400),("Equipment","Intraoral Camera",3990),("Equipment","New Clinic Setup Kit",27600),("Equipment","Dental LED Operating Light",12000),("Equipment","Dental Oil-Free Compressor",25000),("Equipment","Vacuum Pump",20000),("Equipment","Ultrasonic Cleaner",12000),("Equipment","Handpiece Lubrication System",15000),("Equipment","Dental Stool",7000),
("Implantology","Implant Straight Drill",790),("Implantology","Implant Drill Set 15 Piece",18605),("Implantology","Implant Surgical Kit",48000),("Implantology","Implant Guide Kit",23650),("Implantology","Micro Trephine Drill",1495),("Implantology","Drill Extender",840),("Implantology","Titanium Abutment Screw Pack",1190),("Implantology","Basal Implant Kit",10995),("Implantology","Trephine Bur Set",7725),("Implantology","Bone Profile Drill",4500),("Implantology","Lindemann Drill",885),("Implantology","Zygomatic Drill",2500),
]

def slug(s): return s.lower().replace("/","-").replace(" ","-").replace("&","and").replace("+","plus")

def seed():
    Base.metadata.create_all(bind=engine); db=SessionLocal()
    try:
        if db.scalar(select(User).where(User.email=="admin@example.com")): print("Already seeded"); return
        cats={}
        for i,(c,_,_) in enumerate(CATALOG):
            if c not in cats:
                obj=Category(name=c,slug=slug(c),sort_order=i); db.add(obj); db.flush(); cats[c]=obj
        brands=[]
        for name in ["GI","GDC","Waldent","3M","Shofu","GC","Hu-Friedy","Ammdent","Sure Endo","Generic Professional"]:
            b=Brand(name=name); db.add(b); db.flush(); brands.append(b)
        suppliers=[]
        for i,name in enumerate(["Prime Dental Supplies","Medline India Partners","OralCare Distribution","Apex Healthcare Trade"]):
            s=Supplier(name=name,email=f"supplier{i+1}@example.com",lead_time_days=3+i,fill_rate=Decimal(94+i)); db.add(s); db.flush(); suppliers.append(s)
        manufacturers=[]
        for name in ["GDC India","Waldent","3M India","Shofu","GC Dental","Generic OEM"]:
            m=Manufacturer(name=name); db.add(m); db.flush(); manufacturers.append(m)
        for idx,(cat,name,benchmark) in enumerate(CATALOG,1):
            brand=brands[idx%len(brands)]; supplier=suppliers[idx%len(suppliers)]; m=manufacturers[idx%len(manufacturers)]
            p=Product(name=name,sku=f"{cat[:3].upper().replace(' ','')}-{idx:04d}",category_id=cats[cat].id,brand_id=brand.id,supplier_id=supplier.id,manufacturer_id=m.id,description=f"{name} for professional dental and healthcare procurement.",pack_size="1 unit",unit="unit")
            db.add(p); db.flush(); b=Decimal(str(benchmark)); selling=(b*Decimal("0.92") if b<50000 else b); cost=selling*Decimal("0.70"); db.add(Price(product_id=p.id,market_benchmark_price=b,mrp=b, supplier_cost=cost,landed_cost=cost*Decimal("1.05"),our_selling_price=selling,bulk_price=selling*Decimal("0.97"),price_source="public Indian market benchmark",price_confidence="indicative")); db.add(Inventory(product_id=p.id,on_hand=80+(idx%120),incoming=20+(idx%40),reorder_level=20))
        org=Organization(name="Sunrise Dental Clinic",customer_type="multi_chair_clinic",gstin="27DEMO1234F1Z5"); db.add(org); db.flush()
        db.add(User(name="Dr. Rahul Sharma",email="doctor@example.com",password_hash=hash_password("Demo@12345"),role="owner",organization_id=org.id))
        db.add(User(name="Admin User",email="admin@example.com",password_hash=hash_password("Admin@12345"),role="admin"))
        db.add(User(name="Supplier Demo",email="supplier@example.com",password_hash=hash_password("Supplier@12345"),role="supplier",supplier_id=suppliers[0].id))
        db.flush()
        products=db.scalars(select(Product).limit(12)).all()
        for day in range(1,9):
            o=Order(order_number=f"SEED-{day:03d}",organization_id=org.id,status="delivered",created_at=__import__('datetime').datetime.now(__import__('datetime').timezone.utc)-__import__('datetime').timedelta(days=day*8)); db.add(o); db.flush(); sub=Decimal(0)
            for j,p in enumerate(products[:4]):
                qty=5+(day+j)%10; line=p.price.our_selling_price*qty; sub+=line; db.add(OrderItem(order_id=o.id,product_id=p.id,quantity=qty,unit_price=p.price.our_selling_price,line_total=line))
            o.subtotal=sub; o.tax=(sub*Decimal("0.18")).quantize(Decimal("0.01")); o.total=o.subtotal+o.tax
        for po_idx, supplier in enumerate(suppliers,1):
            po=PurchaseOrder(po_number=f"PO-SEED-{po_idx:03d}",supplier_id=supplier.id,status="received" if po_idx%2 else "confirmed",total=Decimal("128000")+Decimal(str(po_idx*17000)),expected_date=__import__('datetime').datetime.now(__import__('datetime').timezone.utc)+__import__('datetime').timedelta(days=po_idx*2))
            db.add(po); db.flush()
            for p in products[:3]:
                qty=40+po_idx*5; cost=p.price.supplier_cost; db.add(PurchaseOrderItem(purchase_order_id=po.id,product_id=p.id,quantity=qty,received_quantity=qty if po.status=="received" else 0,unit_cost=cost,line_total=cost*qty))
        db.commit(); print(f"Seeded {len(CATALOG)} products")
    finally: db.close()

if __name__=="__main__": seed()
