import { FormEvent, useState } from 'react';
import { ArrowRight, Building2, HeartPulse, LockKeyhole, Mail, UserRound } from 'lucide-react';
import { api } from '../lib/api';
import { User } from '../App';

export function AuthPage({onLogin}:{onLogin:(u:User)=>void}){
  const [email,setEmail]=useState('doctor@example.com'); const [password,setPassword]=useState('Demo@12345'); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const t=await api<{access_token:string}>('/auth/login',{method:'POST',body:JSON.stringify({email,password})});localStorage.setItem('token',t.access_token);const u=await api<User>('/auth/me');onLogin(u);}catch(err:any){setError(err.message||'Unable to sign in.');}finally{setBusy(false)}};
  return <div className="auth-screen"><div className="auth-glow"></div><div className="auth-layout"><div className="auth-intro"><div className="brand-row auth-brand"><div className="brand-mark"><HeartPulse size={20}/></div><div><div className="brand-name">dentra</div><div className="brand-sub">procurement OS</div></div></div><div className="intro-chip"><SparkIcon/> BUILT FOR RECURRING PROCUREMENT</div><h1>One calm workspace for every supply decision.</h1><p>Search your catalogue, track spending, reorder the usuals, and keep the clinic supplied without stitching together ten different vendors.</p><div className="intro-points"><span><Check/>Live inventory visibility</span><span><Check/>Database-backed orders</span><span><Check/>Procurement intelligence</span></div></div><div className="auth-card glass-card"><div className="auth-card-head"><div className="auth-icon"><LockKeyhole size={18}/></div><div><div className="eyebrow">SECURE ACCESS</div><h2>Welcome back</h2><p>Enter your workspace credentials.</p></div></div><form onSubmit={submit}><label><span>Email</span><div className="field"><Mail size={16}/><input value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></div></label><label><span>Password</span><div className="field"><LockKeyhole size={16}/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></div></label>{error && <div className="error-box">{error}</div>}<button className="gradient-btn wide-btn" disabled={busy}>{busy?'Signing in…':'Enter workspace'}<ArrowRight size={18}/></button></form><div className="demo-box"><div><strong>Demo access</strong><span>doctor@example.com</span><span>Demo@12345</span></div><div className="demo-sep"></div><div><strong>Admin</strong><span>admin@example.com</span><span>Admin@12345</span></div></div><p className="legal">For local demo use only. Replace demo credentials and secret keys before production.</p></div></div></div>
}
function SparkIcon(){return <span className="spark">✦</span>} function Check(){return <span className="check">✓</span>}
