import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { money } from '../components/ui';
export function CartPage(){
 const nav=useNavigate(); const [cart,setCart]=useState<any[]>([]);
 const sync=()=>{const c=JSON.parse(localStorage.getItem('cart')||'[]');setCart(c);localStorage.setItem('cart_count',String(c.reduce((s:any,x:any)=>s+x.quantity,0)));window.dispatchEvent(new Event('cart-changed'))}; useEffect(sync,[]);
 const update=(id:number,delta:number)=>{const c=cart.map(x=>x.product_id===id?{...x,quantity:Math.max(0,x.quantity+delta)}:x).filter(x=>x.quantity>0);localStorage.setItem('cart',JSON.stringify(c));sync()};
 const remove=(id:number)=>update(id,-999999); const subtotal=useMemo(()=>cart.reduce((s,x)=>s+Number(x.product.our_selling_price)*x.quantity,0),[cart]); const tax=subtotal*.18; const total=subtotal+tax;
 if(!cart.length)return <div className="empty-state glass-card"><div className="empty-icon"><ShoppingBag size={26}/></div><div className="eyebrow">PROCUREMENT CART</div><h1>Your cart is empty.</h1><p>Build an order from the catalogue, or start from your usual procurement list.</p><Link className="gradient-btn" to="/catalogue">Browse catalogue <ArrowRight size={16}/></Link></div>;
 return <div className="page-stack"><section className="hero-row"><div><div className="eyebrow">PROCUREMENT / CART</div><h1>Ready for checkout.</h1><p className="page-sub">Review quantities before the server validates stock and pricing.</p></div></section><section className="checkout-layout"><div className="glass-card line-items"><div className="section-head"><div><h2>{cart.length} line items</h2><p>Your current procurement basket.</p></div></div>{cart.map(x=><div className="line-item" key={x.product_id}><img src={`/product-images/${x.product_id}.svg`} alt=""/><div className="line-main"><Link to={`/product/${x.product_id}`}><strong>{x.product.name}</strong></Link><span>{x.product.brand_name} · {x.product.sku}</span></div><div className="qty"><button onClick={()=>update(x.product_id,-1)}><Minus size={14}/></button><strong>{x.quantity}</strong><button onClick={()=>update(x.product_id,1)}><Plus size={14}/></button></div><strong className="line-total">{money(Number(x.product.our_selling_price)*x.quantity)}</strong><button className="icon-danger" onClick={()=>remove(x.product_id)}><Trash2 size={15}/></button></div>)}</div><aside className="order-summary glass-card"><div className="eyebrow">ORDER SUMMARY</div><div className="summary-row"><span>Subtotal</span><strong>{money(subtotal)}</strong></div><div className="summary-row"><span>GST (18%)</span><strong>{money(tax)}</strong></div><div className="summary-row"><span>Shipping</span><strong>₹0</strong></div><div className="summary-total"><span>Total</span><strong>{money(total)}</strong></div><button className="gradient-btn wide-btn" onClick={()=>nav('/checkout')}>Proceed to checkout <ArrowRight size={16}/></button><p className="summary-note">Final total is recalculated by the backend at order creation.</p></aside></section></div>
}
