import { useEffect, useState } from 'react';
import { Grid2X2, List, Search, ShoppingCart, SlidersHorizontal, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { api } from '../lib/api';
import { ProductCard } from '../components/ui';
export function CataloguePage(){
 const [items,setItems]=useState<any[]>([]); const [cats,setCats]=useState<any[]>([]); const [q,setQ]=useState(''); const [cat,setCat]=useState(''); const [view,setView]=useState<'grid'|'list'>('grid'); const [loading,setLoading]=useState(true); const [showFilters,setShowFilters]=useState(false); const [brand,setBrand]=useState('');
 const load=()=>{setLoading(true); const params=new URLSearchParams({limit:'250'}); if(q)params.set('q',q); if(cat)params.set('category_id',cat); if(brand)params.set('brand_id',brand); api<any[]>(`/products?${params.toString()}`).then(setItems).finally(()=>setLoading(false));};
 useEffect(()=>{api<any[]>('/categories').then(setCats)},[]); useEffect(()=>{const t=setTimeout(load,180);return()=>clearTimeout(t)},[q,cat,brand]);
 return <div className="page-stack"><section className="hero-row catalogue-hero"><div><div className="eyebrow">PRODUCT CATALOGUE / 232 SKUS</div><h1>Supplies that keep the clinic moving.</h1><p className="page-sub">Search instruments, materials, equipment and consumables from one procurement workspace.</p></div><Link to="/cart" className="cart-summary gradient-btn"><ShoppingCart size={17}/> Cart <span>{Number(localStorage.getItem('cart_count')||0)}</span></Link></section>
  <section className="catalogue-toolbar glass-card"><div className="search-box"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search product, SKU, brand, category…"/></div><div className="toolbar-actions"><button className="filter-btn" onClick={()=>setShowFilters(v=>!v)}><SlidersHorizontal size={16}/> Filters</button><div className="category-chips"><button className={!cat?'selected':''} onClick={()=>setCat('')}>All</button>{cats.slice(0,8).map(c=><button key={c.id} className={cat===String(c.id)?'selected':''} onClick={()=>setCat(String(c.id))}>{c.name}</button>)}</div><div className="view-switch"><button className={view==='grid'?'active':''} onClick={()=>setView('grid')}><Grid2X2 size={16}/></button><button className={view==='list'?'active':''} onClick={()=>setView('list')}><List size={16}/></button></div></div></section>
  {showFilters && <section className="filter-drawer glass-card"><div><span className="eyebrow">SMART FILTERS</span><h3>Refine catalogue</h3></div><div className="filter-row"><label>Brand<select value={brand} onChange={e=>setBrand(e.target.value)}><option value="">All brands</option><option value="2">GDC</option><option value="3">Waldent</option><option value="4">3M</option><option value="5">Shofu</option></select></label><label>Availability<select><option>Any status</option><option>In stock</option><option>Low stock</option></select></label><label>Sort<select><option>Relevance</option><option>Price low → high</option><option>Price high → low</option></select></label><button className="ghost-btn" onClick={()=>{setBrand('');setCat('');setQ('')}}><X size={15}/> Clear filters</button></div></section>}
  <section className="catalogue-meta"><span>{loading?'Loading catalogue…':`${items.length} products`}</span><span>{cat?cats.find(c=>String(c.id)===cat)?.name:'All categories'}</span></section>
  {view==='grid'?<div className="catalogue-grid">{items.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<div className="catalogue-list glass-card">{items.map(p=><Link to={`/product/${p.id}`} className="catalogue-list-row" key={p.id}><img src={`/product-images/${p.id}.svg`} alt=""/><div><strong>{p.name}</strong><span>{p.brand_name} · {p.sku} · {p.pack_size}</span></div><span className="muted">{p.category_name}</span><strong>₹{Number(p.our_selling_price).toLocaleString('en-IN')}</strong><span className="stock-inline">{p.available>0?'In stock':'Out of stock'}</span></Link>)}</div>}
 </div>
}
