import { FormEvent, useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2, ChevronRight, MapPin, ShieldCheck } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { api } from '../lib/api';
import { money } from '../components/ui';
export function CheckoutPage(){
 const nav=useNavigate(); const cart=JSON.parse(localStorage.getItem('cart')||'[]'); const [busy,setBusy]=useState(false); const [done,setDone]=useState<any>(); const [error,setError]=useState(''); const [notes,setNotes]=useState('Please deliver during clinic hours.');
 const subtotal=useMemo(()=>cart.reduce((s:any,x:any)=>s+Number(x.product.our_selling_price)*x.quantity,0),[cart]); const tax=subtotal*.18; const total=subtotal+tax;
 if(done)return <div className="success-screen glass-card"><div className="success-orb"><CheckCircle2 size={34}/></div><div className="eyebrow">ORDER CREATED</div><h1>{done.order_number}</h1><p>Your procurement order is confirmed and reserved against available inventory.</p><div className="success-total">{money(Number(done.total))}</div><div className="success-actions"><Link className="gradient-btn" to={`/orders/${done.id}`}>View order <ChevronRight size={16}/></Link><Link className="ghost-btn" to="/catalogue">Continue shopping</Link></div></div>;
 if(!cart.length)return <div className="empty-state glass-card"><h1>Nothing to checkout.</h1><Link className="gradient-btn" to="/catalogue">Browse catalogue</Link></div>;
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const payload=await api<any>('/orders',{method:'POST',body:JSON.stringify({items:cart.map((x:any)=>({product_id:x.product_id,quantity:x.quantity}))})});setDone(payload);localStorage.removeItem('cart');localStorage.setItem('cart_count','0');}catch(err:any){setError(err.message||'Could not create order.')}finally{setBusy(false)}};
 return <div className="page-stack"><Link to="/cart" className="back-link"><ArrowLeft size={16}/> Back to cart</Link><section className="hero-row"><div><div className="eyebrow">CHECKOUT / FINAL REVIEW</div><h1>Place procurement order.</h1><p className="page-sub">Your order is server-validated before inventory is reserved.</p></div></section><section className="checkout-layout"><form className="glass-card checkout-form" onSubmit={submit}><div className="form-section"><div className="section-head"><div><h2>Delivery</h2><p>Using the organisation’s current default address.</p></div></div><div className="address-card"><div className="address-icon"><MapPin size={18}/></div><div><strong>Sunrise Dental Clinic</strong><span>Mumbai, Maharashtra · GSTIN 27DEMO1234F1Z5</span><span>Default delivery address · Demo workspace</span></div></div></div><div className="form-section"><div className="section-head"><div><h2>Order note</h2><p>Optional instructions for operations.</p></div></div><textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={4}/></div>{error&&<div className="error-box">{error}</div>}<button className="gradient-btn wide-btn" disabled={busy}>{busy?'Creating order…':'Place order'} <ChevronRight size={16}/></button><div className="security-note"><ShieldCheck size={15}/><span>Prices, stock and totals are validated by FastAPI before the order is committed.</span></div></form><aside className="order-summary glass-card"><div className="eyebrow">ORDER PREVIEW</div>{cart.map((x:any)=><div className="preview-line" key={x.product_id}><img src={`/product-images/${x.product_id}.svg`} alt=""/><div><strong>{x.quantity} × {x.product.name}</strong><span>{x.product.sku}</span></div><b>{money(Number(x.product.our_selling_price)*x.quantity)}</b></div>)}<div className="summary-divider"></div><div className="summary-row"><span>Subtotal</span><strong>{money(subtotal)}</strong></div><div className="summary-row"><span>GST</span><strong>{money(tax)}</strong></div><div className="summary-total"><span>Total</span><strong>{money(total)}</strong></div></aside></section></div>
}
