import { useEffect, useState } from 'react';
import { ArrowLeft, Check, Heart, Minus, Plus, ShieldCheck, ShoppingCart, Sparkles } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { api } from '../lib/api';
import { ProductCard, money, Pill } from '../components/ui';

export function ProductPage(){
 const {productId}=useParams(); const nav=useNavigate(); const [p,setP]=useState<any>(); const [qty,setQty]=useState(1); const [related,setRelated]=useState<any[]>([]); const [toast,setToast]=useState('');
 useEffect(()=>{api<any>(`/products/${productId}`).then(setP); if(productId)api<any[]>(`/products?limit=6`).then(setRelated)},[productId]);
 if(!p)return <div className="loading-panel glass-card">Loading product…</div>;
 const add=()=>{const cart=JSON.parse(localStorage.getItem('cart')||'[]');const i=cart.findIndex((x:any)=>x.product_id===p.id);if(i>=0)cart[i].quantity+=qty;else cart.push({product_id:p.id,quantity:qty,product:p});localStorage.setItem('cart',JSON.stringify(cart));localStorage.setItem('cart_count',String(cart.reduce((s:any,x:any)=>s+x.quantity,0)));window.dispatchEvent(new Event('cart-changed'));setToast(`${p.name} added to your procurement cart`);setTimeout(()=>setToast(''),2200)};
 return <div className="page-stack"><Link to="/catalogue" className="back-link"><ArrowLeft size={16}/> Back to catalogue</Link><section className="product-detail"><div className="product-visual glass-card"><div className="product-visual-glow"></div><img src={`/product-images/${p.id}.svg`} alt={p.name}/><div className="visual-badge"><ShieldCheck size={14}/> Procurement verified</div></div><div className="product-copy"><div className="eyebrow">{p.category_name.toUpperCase()} / {p.sku}</div><h1>{p.name}</h1><div className="product-subline"><span>{p.brand_name}</span><span>•</span><span>{p.pack_size}</span><span>•</span><span>{p.unit}</span></div><p className="product-description">{p.description}</p><div className="price-panel glass-card"><div><span>OUR PRICE</span><strong>{money(Number(p.our_selling_price))}</strong><small>Market benchmark {money(Number(p.market_benchmark_price))}</small></div><Pill tone="teal">{Number(p.available)>0?'IN STOCK':'OUT OF STOCK'}</Pill></div><div className="purchase-row"><div className="qty"><button onClick={()=>setQty(q=>Math.max(1,q-1))}><Minus size={15}/></button><strong>{qty}</strong><button onClick={()=>setQty(q=>Math.min(100,q+1))}><Plus size={15}/></button></div><button className="gradient-btn big-btn" onClick={add}><ShoppingCart size={17}/> Add to cart</button><button className="ghost-btn icon-only" title="Save"><Heart size={17}/></button></div>{toast&&<div className="success-toast"><Check size={15}/>{toast}</div>}<div className="product-assurance"><div><Check size={15}/><span>Server-validated pricing</span></div><div><Check size={15}/><span>Inventory-aware ordering</span></div><div><Check size={15}/><span>Reorderable from history</span></div></div></div></section><section className="detail-panels"><div className="glass-card"><div className="section-head"><div><h2>Procurement data</h2><p>Operational details for purchasing decisions.</p></div></div><div className="spec-grid"><Spec label="SKU" value={p.sku}/><Spec label="Pack size" value={p.pack_size}/><Spec label="Brand" value={p.brand_name}/><Spec label="Category" value={p.category_name}/><Spec label="Available" value={`${p.available} ${p.unit}s`}/><Spec label="Price confidence" value="Indicative"/></div></div><div className="glass-card intelligence-card"><div className="eyebrow">PROCUREMENT INTELLIGENCE</div><h2>Make the next order easier.</h2><p>This product becomes part of the clinic’s buying history after purchase, enabling reorder signals and saved procurement workflows.</p><div className="intel-row"><Sparkles size={16}/><span>Typical reorder logic is rule-based in the MVP.</span></div></div></section><section><div className="section-head"><div><h2>Related supplies</h2><p>Keep the rest of the workflow in the same workspace.</p></div></div><div className="catalogue-grid related-grid">{related.filter(x=>x.id!==p.id).slice(0,4).map(x=><ProductCard key={x.id} product={x}/>)}</div></section></div>
}
function Spec({label,value}:{label:string,value:string}){return <div className="spec"><span>{label}</span><strong>{value}</strong></div>}
